---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```{r}
library(tidyverse)
library(janitor)
```

# Technical Question

In order to help inform the planning for provision of cancer treatment services 
in NHS Borders, we would like to gain better understanding of the incidence of 
cancer in NHS Borders.

# Read in 5 year incidence summary data set

```{r}
cancer_5yr_data <- read_csv(here::here("5yr_incidence_health_board.csv")) %>% 
  clean_names()

total_incidences_data <- read_csv(here::here("Total_incidences_health_board.csv")) %>% 
  clean_names()
```

# Filter for NHS Borders data only

```{r}
borders_cancer_5yr <- cancer_5yr_data %>% 
  filter(hb == "S08000016")

total_incidences_borders <- total_incidences_data %>% 
  filter(hb == "S08000016")
```

# Plot of Total Cancer Incidences

```{r}
total_cancer_incidences_all <- total_incidences_borders %>% 
  filter(cancer_site == "All cancer types") %>% 
  filter(sex == "All") %>% 
  ggplot(aes(x = year, y = incidences_all_ages)) +
  geom_col(fill = "steel blue", alpha = 0.7) +
  labs(title = "Incidences of all Cancer Types: 1996 - 2020",
       x = "Year",
       y = "Number of Incidences (All ages)") +
  scale_x_continuous(n.breaks = 24) +
  theme_bw() +
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5))

total_cancer_incidences_all
```

# Top 5 most prevelant cancers in NHS Borders

```{r}
top_five_prevalent_cancers <- borders_cancer_5yr %>%
  select(cancer_site, sex, incidences_all_ages) %>% 
  filter(sex == "All" & cancer_site != "All cancer types") %>% 
  slice_max(incidences_all_ages, n = 5) %>% 
  mutate(cancer_type = fct_reorder(cancer_site, incidences_all_ages)) %>% 
  ggplot(aes(x = cancer_type , y = incidences_all_ages)) +
  geom_col(fill = "red", alpha = 0.7) +
  coord_flip() +
  labs(title = "5 Most Prevalent Cancers in NHS Borders Last 5 Years",
       x = "Cancer Site",
       y = "Total Incidences (All ages)") +
  theme_bw()

top_five_prevalent_cancers
```

```{r}
age_top5_cancers <- borders_cancer_5yr %>%
  select(cancer_site, sex, incidences_age_under5:incidences_age85and_over) %>%
  rename(incidences_age05to09 = incidences_age5to9) %>% 
  filter(cancer_site %in% c("Non-melanoma skin cancer", "Basal cell carcinoma of the skin",
                            "Trachea, bronchus and lung", "Colorectal cancer",
                            "Breast") & sex == "All") %>% 
  pivot_longer(cols = incidences_age_under5:incidences_age85and_over, 
               names_to = "age_group", values_to = "count") %>% 
  ggplot(aes(x = age_group, y = count)) +
  geom_col(fill = "steel blue", alpha = 0.8) +
  coord_flip() +
  facet_wrap(~cancer_site) +
  theme_bw() +
  labs(x = "Age Group",
       y = "Number of Incidences")
  
age_top5_cancers
```

```{r}
mean_scotland_cancer <- total_incidences_data %>% 
  filter(cancer_site == "All cancer types" & hb != "S08000016") %>% 
  filter(sex == "All") %>% 
  group_by(year) %>% 
  summarise(avg_cancer_incidences = mean(incidences_all_ages)) %>% 
  ggplot(aes(x = year, y = avg_cancer_incidences)) +
  geom_col(fill = "tomato") +
  scale_x_continuous(n.breaks = 24) +
  theme_bw() +
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5))

mean_scotland_cancer
```

```{r}
# trial for dodged plot 
x <- total_incidences_data %>% 
  filter(cancer_site == "All cancer types" & hb != "S08000016") %>% 
  filter(sex == "All") %>% 
  group_by(year) %>% 
  summarise(incidences_all_ages = mean(incidences_all_ages))

y <- total_incidences_borders %>% 
  filter(cancer_site == "All cancer types") %>% 
  filter(sex == "All")

bind_data <- bind_rows(x, y)
```

```{r}
health_board <- bind_data %>% 
  mutate(health_board = if_else(incidences_all_ages < 1000, "Borders", "Scotland"), .after = 1)

health_board
```

```{r}
health_board %>% 
  ggplot(aes(x = year, y = incidences_all_ages, fill = health_board)) +
  geom_col(position = "dodge") +
  scale_x_continuous(n.breaks = 24) +
  scale_y_continuous(n.breaks = 10) +
  theme_bw() +
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5)) +
  labs(title = "Total Incidences of Cancer in Borders v Scotland",
       x = "",
       y = "",
       fill = "Health Board")
```





```{r}
total_incidences_borders %>% 
  filter(cancer_site == "All cancer types") %>% 
  filter(sex == "All") %>% 
  ggplot(aes(x = year, y = incidences_all_ages, stat = identity)) +
  geom_col(position = "dodge", alpha = 0.7) +
  labs(title = "Incidences of all Cancer Types: 1996 - 2020",
       x = "Year",
       y = "Number of Incidences (All ages)") +
  scale_x_continuous(n.breaks = 24) +
  theme_bw() +
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5))

total_cancer_incidences_all
```

